"""create drowsiness_event table

Revision ID: 0be054e3435f
Revises: 
Create Date: 2025-06-12 11:26:14.191593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be054e3435f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drowsinessevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_identification', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('ear', sa.Float(), nullable=False),
    sa.Column('mar', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drowsinessevent_id'), 'drowsinessevent', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drowsinessevent_id'), table_name='drowsinessevent')
    op.drop_table('drowsinessevent')
    # ### end Alembic commands ###
